create database ecommerce;
use ecommerce;

create table suppliers(
supplier_id int primary key,
supplier_name varchar(30),
country varchar(50)
);

create table products(
product_id int primary key,
product_name varchar(30),
category varchar(30),
price float,
supplier_id int,
foreign key(supplier_id) references suppliers(supplier_id)
);


create table customers(
customer_id int primary key,
customer_name varchar(40),
signup_date date
);

alter table customers
add(
city varchar(30),
state varchar(30));


create table orders(
order_id int primary key,
customer_id int,
order_date date,
order_status varchar(10),
payment_method varchar(20),
foreign key(customer_id) references customers(customer_id)
);

create table shipments(
shipment_id int primary key,
order_id int,
shipping_date date,
deliver_status varchar(10),
foreign key(order_id) references orders(order_id)
);

create table order_items(
order_item int,
order_id int,
product_id int,
quantity int ,
foreign key(order_id) references orders(order_id),
foreign key(product_id) references products(product_id)
);

#BUCKET 1: BASIC SQL

#Display all customers who signed up in the last 6 months.
select customer_name , signup_date from customers
where datediff(now() , signup_date) < 6;

#Get list of distinct product categories.
select distinct(category) from products;

#Find all orders with payment method = 'UPI'.
select product_name , category 
from products join order_items
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id 
where payment_method = "UPI";

#Show all products priced above ₹300.
select product_name , category , price from products 
where price >300;

#Count total number of orders.
select sum(order_id) from orders ;

#List all suppliers from a specific country.
select supplier_name , country from suppliers
where country = "mali";


#BUCKET 2: AGGREGATIONS & GROUP BY


#Total revenue generated by the platform.
select payment_method , round(sum(price*quantity),2) as revenue 
from products join order_items 
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id  
group by payment_method;

#Total number of customers in each state.
select sum(customer_id) , state from customers
group by state; 

#Average product price per category.
select  category , round(avg(price),2) as avg_price  from products
group by category;

#Number of orders per payment method.
select sum(order_id) as Number_of_orders  , payment_method from orders
group by payment_method ;

#Total quantity sold for each product.
select product_name , sum(quantity)  
from products join order_items 
on products.product_id = order_items.product_id
group by product_name;

#Percentage of orders by order_status.
select order_status , count(*), round(count(*)*100/ (select count(*) from orders),1) as percentage
from orders
group by order_status ;

#BUCKET 3: JOINS

#Show customer name along with total amount they spent.
select customer_name , round(sum(price*quantity),2) as total_amount  from customers
join orders
on customers.customer_id = orders.customer_id
join order_items
on orders.order_id = order_items.order_id
join products 
on products.product_id = order_items.product_id
WHERE orders.order_status = 'Completed'
group by customer_name;


#List order_id, order_date, product_name, quantity for each order.
select o.order_id, order_date, product_name , quantity 
from orders o join order_items oi 
on o.order_id = oi.order_id
join products p 
on oi.product_id = p.product_id;

#Find total revenue generated by each product category.
select category , round(sum(price*quantity),2) as revenue 
from products join order_items 
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id  
group by category;

#Display supplier name with products they supply.
select supplier_name , product_name , category , price 
from suppliers s join products p
on s.supplier_id = p.supplier_id;

# Show order_id with its delivery_status.
select order_id , order_status
from orders;

#BUCKET 4: DATE & TIME ANALYSIS

#Monthly revenue trend.
select  month(order_date) as mon, round(sum(price*quantity),2) as revenue 
from products join order_items 
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id  
group by mon 
order by mon ;

#Number of orders per month.
select  month(order_date) as mon, sum(order_id) as orders
from orders
group by mon
order by mon;

#Find peak order month.
select  month(order_date) as mon, sum(order_id) as orders
from orders
group by mon
order by orders desc 
limit 3;

#Count orders placed in last 30 days.
select  sum(order_id)  from orders
where datediff(now() , date(order_date)) < 30;

#Average revenue per month.
select mon, round(Avg(revenue), 2) AS avg_revenue from 
(select  month(order_date) as mon, round(sum(price*quantity),2) as revenue 
from products join order_items 
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id  
group by mon ) t 
group by mon
order by mon;

#BUCKET 5: SUBQUERIES

-- Find products priced higher than average price.
select product_name , category , price from products where price >
(select round(avg(price),2) as average from products);

-- Find customers whose total spending is above average customer spending.
select customer_name ,round( sum(price*quantity) ,2) as amount from customers c join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p 
on p.product_id = oi.product_id
where o.order_status = "Completed"
group by customer_name
having sum(p.price * oi.quantity)  > 
(select round( avg(quantity * price) , 2)  as avearage from order_items oi
join products p 
on p.product_id = oi.product_id) ;

-- Identify product categories contributing more than 50% of total revenue.
select category , percentage  from  
(select category, round(count(*)*100/ (select count(*) from orders),1) as percentage
from order_items oi
join products p
on oi.product_id =p.product_id 
group by category) t 
where percentage >50;

-- Find suppliers supplying products priced above overall average.
select distinct supplier_name , price 
from products p
join suppliers s
on p.supplier_id = s.supplier_id
where price > (select avg(price) from products );

-- BUCKET 6: WINDOW FUNCTIONS

-- Rank products by total revenue.
select products.product_id , product_name , round(sum(price*quantity),2) as revenue ,
rank() over ( order by sum(price*quantity) desc )  
from products join order_items 
on products.product_id = order_items.product_id
join orders on orders.order_id =  order_items.order_id  
group by products.product_id , product_name;


-- Top 3 products by sales quantity in each category.
select  category ,product_name ,total_quantity,rank_in_category from (
SELECT p.category , p.product_name , SUM(oi.quantity) AS total_quantity,
RANK() OVER (PARTITION BY p.category ORDER BY SUM(oi.quantity) DESC) AS rank_in_category
FROM products p JOIN order_items oi 
ON p.product_id = oi.product_id
group by category , product_name
order by rank_in_category) t
where rank_in_category <4;

-- Rank customers based on total spending
select c.customer_id , customer_name , round(sum(price* quantity),2) as revenue , rank()over(order by sum(price* quantity) desc) as ranks
from customers c JOIN orders o 
ON c.customer_id = o.customer_id
JOIN order_items oi 
ON o.order_id = oi.order_id
JOIN products p 
ON oi.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name;

-- Running total of monthly revenue
select month, round(sum(revenue) over(order by month),2) as running_total from
(select month(order_date) as month ,round(sum(price* quantity),2) as revenue  
from orders o join order_items oi 
on o.order_id = oi.order_id
join products p
on p.product_id = oi.product_id
group by month(order_date)) t;

-- Percentage contribution of each category to total revenue 
select category ,round(revenue,2) ,revenue *100 / sum(sum(revenue)) over() as percentage from (
select p.category, sum(p.price * oi.quantity) as revenue
from products p join order_items oi 
on p.product_id = oi.product_id
group by p.category ) t
group by category;

# BUCKET 7: BUSINESS & PERFORMANCE ANALYSIS

-- Revenue generated by each supplier.
select supplier_name , round(sum(price*quantity),2) as revenue  
from suppliers s join products p
on p.supplier_id  = s.supplier_id
join order_items oi
on oi.product_id = p.product_id
group by supplier_name ;


-- which supplier country generates highest revenue?
select supplier_name , round(sum(price*quantity),2) as revenue  
from suppliers s join products p
on p.supplier_id  = s.supplier_id
join order_items oi
on oi.product_id = p.product_id
group by supplier_name
order by revenue 
limit 1 ;

-- Compare total orders vs delivered orders.
select order_status ,c, c/sum(c) over() from (
select order_status , count(order_id) as c
from orders
group by order_status) t;

-- BUCKET 8: ADVANCED / CASE STUDY QUESTIONS

-- Find categories with declining sales month-over-month.
select category , month ,revenue  round(revenue - lag(revenue) over(partition by category order by month),2)
from (
select category,  date_format(order_date,"%Y-%m") as month ,round(sum(price*quantity),2) as revenue 
from products p join order_items oi
on p.product_id = oi.product_id
join orders o
on o.order_id = oi.order_id
group by category , month )t ;

-- Average delivery status performance per month
select date_format(order_date,"%y-%m") as month,
round(avg(case when order_status ="Completed" then 1 else 0 end)*100,2)
from orders 
group by month
order by month;

-- Customer retention — repeat vs one-time customers 
select customer_id , case when order_count = 1 then "one-time customer" else "repeat customer"end as cus_type
from(
select customer_id , count(order_id) as order_count
from orders
group by customer_id)t;

# Cohort analysis based on signup month
select date_format(signup_date , "%y-%m")  as month, count(c.customer_id)
from customers c join orders o
on o.customer_id = c.customer_id
group by month;

-- Flag high-value orders (order value > ₹1000)
select o.order_id ,round( sum(price * quantity),2) as order_value ,
case when sum(price * quantity) >1000 then 'high' else 'low' end as flag
from orders o join order_items oi
on o.order_id = oi.order_id
join products p 
on oi.product_id = p.product_id
group by o.order_id;





